services:
  # MySQL服务
  pro_mysql:
    image: mysql:8.0
    container_name: pro_roll_video_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "33306:3306"
    volumes:
      - ./app/services/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - pro_roll_video_net
    command: --default-authentication-plugin=mysql_native_password

  # Redis服务
  pro_redis:
    image: redis:7.0
    container_name: pro_roll_video_redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "36379:6379"
    volumes:
      - ./app/services/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data/redis
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    restart: unless-stopped
    networks:
      - pro_roll_video_net

  # 视频场景分割服务
  pro_roll_video:
    image: catchoco/roll-video:new-supervisor
    container_name: pro_roll_video_serve
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 4G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility,graphics
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "6000:6000"
    restart: unless-stopped
    command: >
      sh -c "supervisord -n -c /app/supervisor-conf/supervisord.conf"
    healthcheck:
      test: nvidia-smi || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 2s
    networks:
      - pro_roll_video_net

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  pro_roll_video_net:
    driver: bridge
