fastapi>=0.68.0
uvicorn>=0.15.0
python-multipart>=0.0.5
pydantic>=2.7.0
pydantic-settings>=2.2.0
python-dotenv>=0.19.0
oss2
sqlalchemy
pymysql
celery
flask
aiohttp
redis
celery[redis]
aiofiles
httpx

# roll-video 基础服务所需
blinker >= 1.9.0
certifi >= 2025.4.26
charset-normalizer >= 3.4.2
click >= 8.1.8
decorator >= 5.2.1
ffmpeg-python >= 0.2.0
future >= 1.0.0
gunicorn >= 23.0.0
idna >= 3.10
imageio >= 2.37.0
imageio-ffmpeg >= 0.6.0
itsdangerous >= 2.2.0
Jinja2 >= 3.1.6
llvmlite >= 0.44.0
MarkupSafe >= 3.0.2
moviepy >= 2.1.2
numba >= 0.61.2
numpy >= 2.2.5
opencv-python >= 4.11.0.86
packaging >= 25.0
pillow >= 10.4.0
pip >= 22.0.2
proglog >= 0.1.11
psutil >= 7.0.0
python-dotenv >= 1.1.0
requests >= 2.32.3
setuptools >= 59.6.0
tqdm >= 4.67.1
urllib3 >= 2.4.0
Werkzeug >= 3.1.3
wheel >= 0.37.1